import { step } from './utils';
import type { ElectionStep } from '@/types';

// --- BRAZIL (BR) ---
export const BR_BEGINNER: ElectionStep[] = [
  step('br_b1', 1, 'Is voting mandatory?', 'Brazil\'s voting rules.',
    'In Brazil, voting is a constitutional obligation for all literate citizens between the ages of 18 and 70. For those who are 16 or 17 years old, or over 70, as well as for illiterate citizens, voting is optional. Failure to vote without a valid justification can result in small fines and restrictions on obtaining a passport, taking public exams, or receiving government loans.',
    'Mandatory for adults 18-70; optional for teens and seniors.',
    'Ongoing',
    ['Brazilian Citizenship', 'Age 18-70 (Mandatory)', 'Age 16-17 or 70+ (Optional)', 'Voter Registration (Título de Eleitor)', 'No suspended political rights'],
    ['Keep your status regular to avoid fines', 'Use the e-Título app to check your status', 'Justify your absence via the app if you can\'t vote', 'Volunteer as a Mesário (poll worker) for benefits'],
    'When does voting become mandatory?', ['16', '18', '21', '70'], 1, '18 is the threshold.'),
  step('br_b2', 2, 'E-Título and Biometrics', 'Digital registration.',
    'The TSE (Superior Electoral Court) has modernized voting through the "e-Título" app, which serves as a digital version of your voter ID. It provides your polling station location and serves as identification if you have registered your biometrics. Biometric registration involves scanning your fingerprints and taking a digital photo, which significantly enhances the security of the identification process at the polls.',
    'Use the app and your fingerprint to vote securely.',
    'Pre-election',
    ['Photo ID', 'e-Título App', 'Biometric registration', 'Updated residential address', 'Smartphone for digital ID'],
    ['Register your biometrics early', 'Download the e-Título app weeks before', 'Check your polling station location in the app', 'Keep your phone charged on election day'],
    'Which app is used?', ['WhatsApp', 'e-Título', 'Gov.br', 'Wallet'], 1, 'e-Título is the official app.'),
  step('br_b3', 3, 'Electronic Voting Machines', 'Safe and disconnected.',
    'Brazil has used a 100% electronic voting system since 1996. The "Urna Eletrônica" is a purpose-built computer that is NOT connected to any network, including the internet or Bluetooth, making it highly secure against external hacking. Each machine undergoes rigorous public testing before each election. You cast your vote by simply typing the candidate\'s number and pressing the green "Confirma" button.',
    'Typing your candidate\'s number is quick and secure.',
    'Election Day',
    ['Candidate numbers (memo)', 'Poll station location', 'Valid identification', 'Knowledge of the ballot order'],
    ['Check the candidate photo on the screen', 'Press "Corrige" if you type the wrong number', 'Wait for the final "Fim" sound', 'Research candidate numbers in advance'],
    'Is the machine online?', ['Yes', 'No', 'Only for results', 'Only in cities'], 1, 'It is completely offline.'),
  step('br_b4', 4, 'The Two-Round System', 'Executive runoffs.',
    'For major executive roles like President or Governor in large cities, Brazil uses a two-round system. If no candidate receives more than 50% of the valid votes (excluding blank and null votes) in the first round, a second round is held between the top two candidates three weeks later. This ensures that the final winner has the support of a majority of the active electorate.',
    'A "final" between the top two candidates.',
    'October (1st and 2nd Rounds)',
    ['Knowledge of runoff dates', 'Understanding of valid votes', 'Candidate platforms', 'Majority support awareness'],
    ['Blank/null votes don\'t count for the total', 'Research the two remaining candidates deeply', 'Check the results on the TSE website', 'The second round is always on the last Sunday of October'],
    'When is the second round?', ['Always', 'If no majority', 'Never', 'If the King says'], 1, 'It ensures majority support.'),
  step('br_b5', 5, 'What to Bring', 'Election day rules.',
    'On election day, you must present a valid photo ID (such as a passport, driving license, or work permit) or your e-Título (if you have biometrics). It is strictly forbidden to take cell phones, cameras, or any recording devices into the voting booth to preserve the secrecy of the vote. You are encouraged to bring a small piece of paper, called a "cola," with the numbers of your chosen candidates.',
    'Leave your phone outside; bring a paper note with your numbers.',
    'Election Day',
    ['Photo ID (RG, CNH, or Passport)', 'Paper note with candidate numbers', 'e-Título (Digital ID)', 'Mask (if health rules apply)'],
    ['Cell phones are strictly banned in the booth', 'A paper "cola" is allowed and encouraged', 'Go early to avoid queues in the heat', 'Leave backpacks and large bags at home'],
    'What can you take in?', ['Cell phone', 'Camera', 'Paper note', 'None'], 2, 'A paper "cola" is allowed.'),
];

// --- AUSTRALIA (AU) ---
export const AU_BEGINNER: ElectionStep[] = [
  step('au_b1', 1, 'Is voting compulsory?', 'Australia\'s unique rule.',
    'In Australia, voting is a legal requirement for all eligible citizens aged 18 and over. This "compulsory voting" system has been in place for federal elections since 1924. If you fail to vote without a valid and sufficient reason, you may be issued a fine (currently around $20 for the first offense). This policy ensures high voter turnout and that the government represents a broad cross-section of the population.',
    'You must vote by law if you are 18+.',
    'Ongoing',
    ['Australian Citizenship', 'Age 18+ on polling day', 'Enrollment with the AEC', 'No mental incapacity (legal definition)', 'No serving a prison sentence of 3+ years'],
    ['Enrol as soon as you turn 18', 'Update your details on the AEC website', 'Check your enrollment status before every election', 'Know your rights for assistance at the booth'],
    'Is voting mandatory?', ['Yes', 'No', 'Only for men', 'Only for landowners'], 0, 'Australia was a pioneer in compulsory voting.'),
  step('au_b2', 2, 'Preferential Voting', 'The 1, 2, 3 system.',
    'Australia uses a "Preferential Voting" system, which is a form of ranked-choice voting. Instead of just picking one candidate, you rank them in order of preference (1, 2, 3...). If your first-choice candidate is eliminated, your vote is transferred to your next preferred candidate. This continues until one candidate receives an absolute majority of votes, ensuring the winner has the broadest possible support.',
    'Don\'t just pick one; rank them all.',
    'Election Day',
    ['Ranked choice knowledge', 'Ballot marking (Numbers only)', 'Candidate preference list', 'Understanding of major vs minor parties'],
    ['Your vote is never "wasted" in this system', 'Mark EVERY box for a valid House vote', 'Check the AEC "How to Vote" guide', 'Research independent candidates carefully'],
    'How do you mark the ballot?', ['Checkmark', 'Numbers (1, 2, 3)', 'X', 'Signature'], 1, 'Numbers are required.'),
  step('au_b3', 3, 'The House and Senate', 'Two ballots, two colors.',
    'On federal election day, you will receive two separate ballot papers. The green ballot is for the House of Representatives, where you choose a local member for your specific electorate. The large white ballot is for the Senate, where you choose representatives for your whole state or territory. For the Senate, you can choose to vote "above the line" (for a party) or "below the line" (for individual candidates).',
    'Two houses, two different voting styles.',
    'Election Day',
    ['House (Green) ballot', 'Senate (White) ballot', 'State/Territory identification', 'Pencil (provided at booth)'],
    ['Vote "above the line" for easy Senate voting', 'Use numbers 1-6 above the line for Senate', 'Ensure you follow the instructions on the ballot paper', 'Ask for help if you find the Senate ballot confusing'],
    'Green ballot color?', ['House', 'Senate', 'Mayor', 'None'], 0, 'Green is for the House of Reps.'),
  step('au_b4', 4, 'The Sausage Sizzle', 'Election day culture.',
    'Voting in Australia is often a community event. Most polling stations, located in local primary schools and community halls, host a "Democracy Sausage" sizzle run by volunteers. Many also hold cake stalls and school fetes. This tradition has become a beloved part of the Australian election day experience, with websites even tracking which polling booths have the best sausage sizzles.',
    'Vote, then get a snack.',
    'Election Day',
    ['Hunger!', 'Small change/cash', 'Community spirit', 'Saturday morning free time'],
    ['Look for the best sausage sizzle in your area', 'Bring cash for the sausage sizzle and cakes', 'Vote early to get the freshest sausages', 'Check "Democracy Sausage" maps online'],
    'What is a "Democracy Sausage"?', ['A law', 'A snack', 'A candidate', 'A medal'], 1, 'It is a beloved tradition.'),
  step('au_b5', 5, 'Where to Vote', 'Local booths.',
    'Federal elections in Australia are always held on a Saturday. You can vote at any polling place in your state or territory on election day, or you can visit an early voting center in the weeks prior if you cannot make it on the day. Polling places are open from 8am to 6pm. Postal voting and telephone voting are also available for those with specific needs or living in remote areas.',
    'Saturdays are for voting.',
    'Saturday Election Day (8am - 6pm)',
    ['Polling station location', 'Electoral district knowledge', 'Voter identification (not always required)', 'Early voting eligibility (if applicable)'],
    ['Absentee voting is available if you are out of your district', 'Check the AEC website for booth locations', 'Avoid the lunchtime rush for shorter queues', 'Keep your voter registration card handy'],
    'Usual day for elections?', ['Tuesday', 'Saturday', 'Sunday', 'Friday'], 1, 'Saturday is the standard.'),
];

// --- CANADA (CA) ---
export const CA_BEGINNER: ElectionStep[] = [
  step('ca_b1', 1, 'Am I Eligible?', 'Canadian citizenship rules.',
    'To vote in a Canadian federal election, you must be a Canadian citizen and at least 18 years old on election day. You must also be registered on the National Register of Electors. Canadians living abroad can vote by special ballot regardless of how long they have been away. Permanent residents and other non-citizens are not eligible to vote in federal elections.',
    'Citizenship and 18 years old.',
    'Ongoing',
    ['Canadian Citizenship', 'Age 18+ by election day', 'National Register of Electors entry', 'Proof of identity', 'Proof of address'],
    ['Check your registration at Elections Canada', 'Register at age 17 to be ready for 18', 'Apply for citizenship if you are a resident', 'Know your rights if you are an overseas voter'],
    'Age?', ['16', '18', '21', '25'], 1, '18 is the law.'),
  step('ca_b2', 2, 'Registration', 'Getting on the list.',
    'Elections Canada maintains the voter list. You can check if you are registered, update your information, or register for the first time online. If you are not registered by election day, you can still register at the polling station just before you vote, as long as you have the required ID. Most Canadians are registered automatically through tax filings if they give consent.',
    'Registration is easy and can even be done when you arrive to vote.',
    'Until Election Day',
    ['ID and Proof of Address', 'Voter Information Card (if received)', 'Tax filing consent (optional)', 'Online registration access'],
    ['Registering in advance saves time at the polls', 'Check your Voter Information Card for accuracy', 'Bring your card and ID together', 'Ask for a language interpreter if needed'],
    'Can you register at the polls?', ['Yes', 'No', 'Only in Yukon', 'Only with a lawyer'], 0, 'Canada allows same-day registration.'),
  step('ca_b3', 3, 'First Past the Post', 'Constituency wins.',
    'Canada uses the "First-Past-the-Post" system for federal elections. The country is divided into 338 electoral districts, also known as ridings. Voters in each riding elect one Member of Parliament (MP) to represent them in the House of Commons. The candidate with the most votes in the riding wins the seat. The leader of the party with the most seats usually becomes the Prime Minister.',
    'Whoever gets the most votes in your area becomes your MP.',
    'Election Day',
    ['Riding/District knowledge', 'Candidate names', 'Party platform summaries', 'Understanding of minority governments'],
    ['The party with the most seats usually forms the government', 'Research the local candidate\'s priorities', 'Understand how a "Confidence" vote works', 'Know the boundaries of your riding'],
    'How many ridings?', ['300', '338', '400', '450'], 1, '338 is the current count.'),
  step('ca_b4', 4, 'Ways to Vote', 'Advance and mail.',
    'Elections Canada provides several ways to vote. You can vote in person on election day at your assigned polling station, or during four days of advance polling. You can also vote at any Elections Canada office across the country before a specific deadline. Finally, you can vote by mail using a special ballot, which is a popular option for students and travelers.',
    'Vote early if you are busy on election day.',
    'Election Day and 4 days of advance polling',
    ['Voter Information Card', 'Special ballot application (for mail)', 'Polling station location', 'Valid identification'],
    ['Bring your Voter Information Card to speed things up', 'Vote at advance polls to avoid crowds', 'Apply for mail-in ballots weeks in advance', 'Check office hours if voting at an EC office'],
    'Advance polling?', ['Yes', 'No', 'Only for military', 'Only for seniors'], 0, 'Advance polls are open for everyone.'),
  step('ca_b5', 5, 'Required ID', 'Proving who you are.',
    'To vote, you must prove your identity and address. There are three options: 1) Present one government-issued photo ID with your name and current address (like a driver\'s license). 2) Present two pieces of ID, both with your name and at least one with your current address (like a health card and a utility bill). 3) If you have no ID, you can declare your identity in writing and have someone else "vouch" for you.',
    'You need ID, but there are many ways to prove it.',
    'Election Day',
    ['Accepted ID (Option 1, 2, or 3)', 'Utility bill or bank statement', 'Witness for vouching (if needed)', 'Voter Information Card'],
    ['Check the list of accepted IDs at elections.ca', 'Ensure your address is current on your ID', 'Someone can vouch for you if you lack ID', 'Expired ID is sometimes accepted (check rules)'],
    'Vouching?', ['Yes', 'No', 'Only in 2024', 'None'], 0, 'Someone can vouch for you if you lack ID.'),
];
