import { step } from './utils';
import type { ElectionStep } from '@/types';

// --- UNITED KINGDOM (GB) ---
export const GB_BEGINNER: ElectionStep[] = [
  step('gb_b1', 1, 'Am I Eligible to Vote?', 'UK voter eligibility rules.',
    'To vote in a UK General Election, you must be a British, Irish, or qualifying Commonwealth citizen. You must also be 18 years or older on polling day and resident in the UK. Some UK citizens living abroad can also register as overseas voters. You must not be a convicted prisoner or otherwise legally disqualified from voting.',
    'You need to be 18 and a citizen of the UK, Ireland, or the Commonwealth.',
    'Ongoing',
    ['Citizenship (UK/Irish/Commonwealth)', 'Age 18+ on polling day', 'UK Resident', 'Registered on the electoral roll', 'Not legally disqualified'],
    ['Register as soon as you move house', 'Check overseas voting rules if abroad', 'Students can register at home and uni (but only vote once)', 'Encourage friends to register'],
    'What is the minimum age for a General Election?', ['16', '18', '21', '25'], 1, 'It is 18 for national elections.'),
  step('gb_b2', 2, 'Registering to Vote', 'The UK registration system.',
    'You must be on the electoral register to vote. You can register online at gov.uk/register-to-vote in about 5 minutes. You will need your National Insurance (NI) number and passport (if living abroad). Once registered, you remain on the list unless you move house or your details change. Every year, councils send a "Canvass Communication" to verify who is living at each address.',
    'You need your NI number to register online.',
    'Until 12 days before polling',
    ['National Insurance Number', 'Current Address details', 'Passport (for overseas)', 'DOB verification'],
    ['Registering helps your credit score!', 'Update your details after marriage or name change', 'Check the register if you haven\'t voted in years', 'Opt-out of the "open register" for privacy'],
    'Where do you register?', ['Post Office', 'gov.uk', 'Police', 'Library'], 1, 'The government website is the place.'),
  step('gb_b3', 3, 'First Past the Post', 'The UK voting system.',
    'The UK uses the "First Past the Post" (FPTP) system. The country is divided into 650 local areas called constituencies. On election day, you vote for one candidate to represent your area in the House of Commons. The candidate who receives the most votes (a plurality) wins the seat, regardless of whether they have a majority. The party with the most seats usually forms the Government.',
    'The person with the most votes wins, even if it is not a majority.',
    'Election Day',
    ['Local candidate knowledge', 'Constituency identification', 'Understanding the ballot paper'],
    ['Check your local candidates online', 'Research party manifestos', 'Attend local "hustings" (debates)', 'Know which constituency you live in'],
    'How many constituencies are there?', ['450', '577', '650', '700'], 2, '650 is the current total.'),
  step('gb_b4', 4, 'Voter ID Requirements', 'New rules for 2023+.',
    'As of 2023, you must show a valid form of photo identification to vote in person at polling stations for General Elections. Accepted IDs include a UK passport, driving license, Blue Badge, or older person\'s bus pass. If you do not have an accepted ID, you can apply for a free "Voter Authority Certificate" online. These rules do not apply to postal voting.',
    'No ID, no vote (unless voting by post).',
    'Election Day (ID required)',
    ['Valid Photo ID (Passport/License)', 'Voter Authority Certificate (if needed)', 'Poll card (helpful but not required)'],
    ['Apply for a free Voter Authority Certificate if you have no ID', 'Check the list of expired IDs that are still accepted', 'Ensure the photo on your ID still looks like you', 'Remind family members about the ID rules'],
    'What is mandatory for in-person voting now?', ['Poll card', 'Photo ID', 'Utility bill', 'Nothing'], 1, 'Photo ID became mandatory in 2023.'),
  step('gb_b5', 5, 'How to Vote', 'Polling stations and deadlines.',
    'On election day, you can vote in person at your assigned polling station between 7am and 10pm. You can also apply to vote by post or by proxy (someone else voting for you). If you vote by post, your ballot must reach the local office by 10pm on election day. Polling stations are often in schools, community centers, or churches.',
    'In person, by mail, or have a friend vote for you.',
    'Election Day (7am - 10pm)',
    ['Polling station location', 'Postal ballot (if applied)', 'Proxy authorization (if applied)', 'Ink pen (provided at station)'],
    ['Post your ballot back early if voting by mail', 'You don\'t need your poll card to vote in person', 'If you forget to post your ballot, drop it at a station', 'Ask poll workers for help if needed'],
    'What time do polls close?', ['6pm', '8pm', '10pm', 'Midnight'], 2, '10pm is the closing time.'),
];

// --- FRANCE (FR) ---
export const FR_BEGINNER: ElectionStep[] = [
  step('fr_b1', 1, 'Am I eligible?', 'French citizenship rules.',
    'To vote in French national elections, you must be a French citizen and at least 18 years old. You must also enjoy your civil and political rights. If you are a citizen of another European Union member state, you can vote in municipal and European elections, but not in presidential or legislative ones. Most young people are now automatically registered when they turn 18.',
    'French nationality and 18 years old are the keys.',
    'Ongoing',
    ['French Citizenship', 'Age 18+', 'Registration on electoral list', 'Civil rights enjoyment', 'Proof of identity'],
    ['18-year-olds are often registered automatically', 'Check your status on service-public.fr', 'Update address if you move within France', 'Keep your voter card safe'],
    'Minimum age?', ['16', '18', '21', '25'], 1, '18 is the legal age.'),
  step('fr_b2', 2, 'Registration', 'Getting on the list.',
    'Registration is mandatory to vote. You can register at any time of the year, but for a specific election, you must register by the 6th Friday before the first round. You can register online at service-public.fr, by mail, or in person at your local town hall (Mairie). You will need a valid ID and a proof of address less than three months old.',
    'Register at least 6 weeks before the vote.',
    'Until 6th Friday before vote',
    ['Valid ID (Passport/CNI)', 'Proof of Address (Utility bill)', 'Registration Form (Cerfa)', 'Town Hall contact'],
    ['Report address changes immediately', 'Register online for the fastest experience', 'Ensure your proof of address is recent', 'Ask for a receipt after registration'],
    'Where to register?', ['Police', 'Town Hall', 'Post Office', 'Bank'], 1, 'Town hall (Mairie) is the place.'),
  step('fr_b3', 3, 'The Two-Round System', 'Runoff mechanics.',
    'France uses a two-round uninominal voting system for presidential and legislative elections. If no candidate wins an absolute majority (over 50%) in the first round, a second round is held two weeks later between the top two candidates. This system encourages the formation of broad political alliances and ensures that the final winner has significant majority support.',
    'Round 1 is for your heart; Round 2 is for your choice.',
    'Sunday and Sunday + 14 days',
    ['Knowledge of runoff dates', 'Understanding of majority rules', 'Candidate platform comparison', 'Dual-ballot strategy'],
    ['The second round is a direct duel', 'Check if your preferred candidate made the cut', 'Abstention in round 2 still impacts the outcome', 'Understand the "republican front" concept'],
    'How many in the 2nd round?', ['All', '3', '2', '1'], 2, 'It is a duel.'),
  step('fr_b4', 4, 'How to Vote', 'Polling station rituals.',
    'On election day, you go to your assigned polling station. You must take a ballot for each candidate (to preserve secrecy) and an envelope. You then enter the voting booth (mandatory), put your chosen ballot in the envelope, and exit. After presenting your ID and voter card to the officials, you slide the envelope into the transparent ballot box. The official then announces "A voté!" while signing the register.',
    'The president says "A voté!" after you slide the envelope.',
    'Election Day',
    ['Photo ID (Passport/CNI)', 'Voter Card (recommended)', 'Knowledge of station location', 'Assigned booth number'],
    ['Booth passage is mandatory', 'Take at least two different ballots', 'Leave your phone in your pocket', 'Polling stations usually open at 8am'],
    'Official phrase?', ['Done', 'A voté!', 'Bravo', 'Next'], 1, 'A voté! is the standard.'),
  step('fr_b5', 5, 'President and Parliament', 'The goals of the vote.',
    'The President of the Republic is the head of state, elected by direct universal suffrage for a five-year term, known as the "Quinquennat." The National Assembly is the lower house of Parliament, where deputies make and vote on laws. If the President and the Assembly majority are from different parties, a "cohabitation" occurs, requiring the President to appoint a Prime Minister from the opposing majority.',
    'You vote for the leader and the law-makers.',
    'Every 5 years',
    ['Candidate platform awareness', 'Knowledge of institutional roles', 'Election calendar awareness', 'Political party understanding'],
    ['A cohabitation occurs when they are from different parties', 'The President cannot serve more than two terms', 'Legislative elections usually follow the Presidential one', 'Research the powers of the Prime Minister'],
    '5-year mandate?', ['Triennat', 'Quinquennat', 'Septennat', 'None'], 1, 'Quinquennat is the name.'),
];

// --- GERMANY (DE) ---
export const DE_BEGINNER: ElectionStep[] = [
  step('de_b1', 1, 'Who can vote?', 'German eligibility.',
    'To vote in German federal elections (Bundestagswahl), you must be a German citizen and at least 18 years old on election day. You must have lived in Germany for at least three months prior to the election. Residents of other EU countries living in Germany can vote in local and European elections, but only German citizens can participate in national elections. You must also not be disqualified from voting by a court order.',
    'Citizenship and 18 years old to join.',
    'Ongoing',
    ['German Citizenship', 'Age 18+ by election day', '3 months residency in Germany', 'Entry in the electoral register', 'No disqualification by court order'],
    ['You will get a notification by mail automatically', 'Check your local Bürgeramt if you haven\'t received mail', 'Apply for registration if you recently returned from abroad', 'Keep your ID card (Personalausweis) valid'],
    'Age?', ['16', '18', '21', '25'], 1, '18 for national elections.'),
  step('de_b2', 2, 'Notification', 'The paper invitation.',
    'About 4 to 6 weeks before the election, every eligible voter receives a "Wahlbenachrichtigung" (election notification) by mail. This letter confirms that you are in the electoral register and tells you the address of your specific polling station. It also includes an application form if you wish to vote by post instead of in person. You should bring this letter and your ID card with you to the polling station.',
    'The letter tells you exactly where to go.',
    '4-6 weeks before',
    ['Registration at current address', 'Mailbox access', 'Valid ID card (Personalausweis)', 'Polling station address'],
    ['Keep the letter safe; it makes voting faster', 'Verify the polling station address early', 'Apply for postal voting if you are traveling', 'Contact your local authority if the mail is missing'],
    'How do you know where to go?', ['Newspaper', 'Mail notification', 'Search online', 'None'], 1, 'The mail notification.'),
  step('de_b3', 3, 'Two Votes', 'Personalized proportionality.',
    'Germany uses a "Personalized Proportional Representation" system where each voter has two votes. The first vote (Erststimme) is for a local candidate in your constituency; the winner here gets a direct seat. The second vote (Zweitstimme) is for a political party list and is much more important, as it determines the overall percentage of seats each party will have in the Bundestag. This system ensures that the parliament reflects the national popular vote.',
    'Local representative vs. National party strength.',
    'Election Day',
    ['Knowledge of local candidates', 'Party platform awareness', 'Understanding of the 5% rule', 'Ballot marking instructions'],
    ['You can split your votes between parties', 'Research the local candidate\'s record', 'The 2nd vote determines the Chancellor\'s party power', 'Ensure you mark only one box for each vote'],
    'Which vote is more important?', ['1st', '2nd', '3rd', 'None'], 1, 'The 2nd vote decides seat counts.'),
  step('de_b4', 4, 'The 5% Hurdle', 'The entry barrier.',
    'To prevent political fragmentation and ensure a stable government, a party must receive at least 5% of the national second votes to enter the Bundestag. If a party fails to meet this threshold, it receives no seats unless it wins at least three direct constituency seats via the first vote. This "Sperrklausel" (blocking clause) encourages voters to consider the viability of smaller parties.',
    'It prevents too many tiny parties from making government hard.',
    'Election Day',
    ['Threshold awareness', 'Coalition knowledge', 'Political stability understanding', 'Current poll tracking'],
    ['Helps keep the parliament stable', 'Research "small" parties carefully', 'Consider if your party will likely pass 5%', 'Understand how "wasted" votes impact coalitions'],
    'Threshold?', ['1%', '3%', '5%', '10%'], 2, '5% is the rule.'),
  step('de_b5', 5, 'Mail Voting', 'Voting from your couch.',
    'If you cannot or do not want to go to a polling station, you can apply for "Briefwahl" (postal voting). Once you receive your documents, you mark the ballot, place it in the blue envelope, and then place that inside the red return envelope along with your signed voting card. No postage stamp is needed if mailed within Germany. Your ballot must reach the election office by 6pm on election Sunday.',
    'Fill out the ballot, put it in the red envelope, and mail it.',
    'Before Election Day',
    ['Postal application form', 'Marked ballot paper', 'Signed polling card (Wahlschein)', 'Blue and Red envelopes'],
    ['Mail it back early; it must arrive by Sunday 6pm', 'Ensure you sign the polling card personally', 'Do not forget to put the ballot in the blue envelope first', 'Drop it in any yellow Deutsche Post box'],
    'Envelope color?', ['Blue', 'Red', 'Yellow', 'White'], 1, 'Red is the return envelope.'),
];
