/**
 * Static fallback content for when Gemini API is unavailable.
 * Ensures the app is fully functional without any API calls.
 * Covers major countries with complete, accurate, and high-depth election content.
 * All content is provided in English as the source language for the translation pipeline.
 */

import type { ElectionStep, KnowledgeLevel } from '@/types';

/** Helper to create a step with required fields */
function step(
  id: string, order: number, title: string, desc: string,
  detailed: string, simple: string, timeline: string,
  reqs: string[], tips: string[], quizQ: string,
  quizOpts: string[], correctIdx: number, hint: string
): ElectionStep {
  return {
    id, order, title, description: desc,
    detailedExplanation: detailed, simpleExplanation: simple,
    timeline, requirements: reqs, tips, status: 'locked',
    microQuizQuestion: { question: quizQ, options: quizOpts, correctIndex: correctIdx, hint },
  };
}

// --- INDIA (IN) ---
const IN_BEGINNER: ElectionStep[] = [
  step('in_b1', 1, 'Am I Eligible to Vote?', 'Basic eligibility check for Indian elections.',
    'To vote in India, you must be a citizen of India and have reached the age of 18 on the qualifying date (usually January 1st of the year of the electoral roll revision). You must be an ordinary resident in the constituency where you want to be registered. Mentally sound persons and those not disqualified by law for corrupt practices are eligible. You cannot be registered in more than one place.',
    'You need to be an Indian citizen and 18 years old to vote.',
    'Ongoing',
    ['Indian Citizenship', 'Age 18+ by qualifying date', 'Ordinary resident in constituency', 'Not disqualified by law', 'Sound mind'],
    ['Check your name on the electoral roll early', 'Update your address if you move house', 'Keep your EPIC card safe', 'Verify eligibility on the ECI portal'],
    'What is the minimum age to vote in India?', ['16', '18', '21', '25'], 1, 'Legal adulthood in India starts at 18.'),
  step('in_b2', 2, 'How to Register as a Voter', 'Getting on the electoral roll.',
    'Registration is the process of getting your name onto the Electoral Roll using Form 6 through the National Voters Service Portal (NVSP) or the Voter Helpline App. You need to provide a passport-sized photo, age proof (like a birth certificate or Aadhaar), and address proof (like a utility bill or bank passbook). Once submitted, a Booth Level Officer (BLO) may visit your home for verification.',
    'Registering is like signing up for a library card — you fill out a form to get access.',
    'At least 3 weeks before election',
    ['Form 6 application', 'Age proof (Aadhaar/Passport)', 'Address proof (Ration card/Bill)', 'Recent passport size photo', 'Mobile number for OTP'],
    ['Apply online for faster processing', 'Track your application status on NVSP', 'Contact your local BLO if delayed', 'Ensure name spelling matches ID documents'],
    'Which form is used for new voter registration?', ['Form 1', 'Form 6', 'Form 7', 'Form 8'], 1, 'Form 6 is for new voters.'),
  step('in_b3', 3, 'Understanding the EVM', 'How Electronic Voting Machines work.',
    'India uses Electronic Voting Machines (EVMs) consisting of a Control Unit (with the officer) and a Balloting Unit (in the booth). When you press the blue button next to your candidate\'s name and symbol, a red light glows, and a long beep sounds. EVMs are battery-operated and not connected to any network, making them immune to hacking via internet or Bluetooth.',
    'The EVM is a secure calculator for your vote.',
    'Election Day',
    ['Voter ID (EPIC)', 'Queue slip from polling desk', 'Identity verification'],
    ['Wait for the beep sound to confirm your vote', 'Check the candidate symbol carefully', 'Do not take photos of the EVM', 'Report any machine malfunction to the officer'],
    'Is the EVM connected to the internet?', ['Yes', 'No', 'Only during counting', 'Only in big cities'], 1, 'Isolation makes it secure.'),
  step('in_b4', 4, 'VVPAT Verification', 'Confirming your vote with paper.',
    'The Voter Verifiable Paper Audit Trail (VVPAT) is an independent system connected to the EVM. It prints a small slip showing the serial number, name, and symbol of the candidate you voted for. The slip is visible through a glass window for 7 seconds before it automatically cuts and falls into a sealed drop box. This allows you to verify that your vote was cast correctly.',
    'The VVPAT is like a grocery receipt you see through a window.',
    'Election Day',
    ['Watch the VVPAT window', 'Verify serial number', 'Confirm candidate symbol'],
    ['Ensure the name on the slip matches your choice', 'Notify the presiding officer if the slip is wrong', 'Wait for the slip to drop before leaving', 'Do not try to touch the paper slip'],
    'How long is the VVPAT slip visible?', ['2 seconds', '7 seconds', '15 seconds', 'Until you leave'], 1, '7 seconds is the standard.'),
  step('in_b5', 5, 'Going to the Polling Booth', 'What to expect on Election Day.',
    'Go to your assigned booth, show your ID to the first polling officer, and get your finger marked with indelible ink by the second officer. You will sign the register and receive a slip. Finally, go to the voting compartment, cast your vote on the EVM, and watch the VVPAT. Mobile phones, cameras, and bags are strictly prohibited inside the voting booth.',
    'Show your ID, get an ink mark, and vote in private.',
    'Election Day',
    ['EPIC Card or 12 alternative Photo IDs', 'Polling station location', 'Voter Slip (optional but helpful)', 'Indelible ink mark'],
    ['Go early to avoid long queues', 'Check your booth number online', 'Maintain silence and discipline', 'Cooperate with security personnel'],
    'Where is the indelible ink applied?', ['Left index finger', 'Right thumb', 'Left thumb', 'Forehead'], 0, 'It is a visible mark on your hand.'),
];

// --- USA (US) ---
const US_BEGINNER: ElectionStep[] = [
  step('us_b1', 1, 'Am I Eligible to Vote?', 'Fundamental requirements for US voters.',
    'To vote in U.S. federal elections, you must be a U.S. citizen (either by birth or naturalization) and at least 18 years old by Election Day. You must also meet your state’s residency requirements. People with felony convictions or mental incapacity may be restricted from voting depending on their state\'s laws. You cannot vote in the US if you are a non-citizen, even if you are a permanent resident.',
    'You need US citizenship and to be 18 years old to vote.',
    'Ongoing',
    ['U.S. Citizenship', 'Age 18+ by Election Day', 'State Residency requirements', 'No disqualifying felony (varies)', 'Proper identification'],
    ['Check your state\'s rules at vote.gov', 'Verify registration status after moving', 'Apply for citizenship if you are a resident', 'Know your rights if you have a disability'],
    'What is the minimum age to vote in US federal elections?', ['16', '18', '21', '25'], 1, 'The 26th Amendment set this.'),
  step('us_b2', 2, 'How to Register to Vote', 'Getting into the system.',
    'Most states require you to register before you can vote. You can register online, by mail, or in person at local election offices, motor vehicle departments (DMV), or recruitment centers. Some states allow "Same Day Registration" where you can register and vote on the same day. Deadlines vary by state, often ranging from 15 to 30 days before the election.',
    'Registering is like signing up for a membership before you can use the service.',
    'Varies by state (usually 30 days before)',
    ['Social Security Number or State ID', 'Proof of residence', 'Completed Registration Form', 'Birth certificate (sometimes)'],
    ['Register early to avoid deadlines', 'Use the National Mail Voter Registration Form', 'Update your name if it changes', 'Check for automatic voter registration in your state'],
    'Which state does NOT require registration?', ['Texas', 'New York', 'California', 'North Dakota'], 3, 'North Dakota is unique.'),
  step('us_b3', 3, 'Primary vs. General Elections', 'The two stages of choosing leaders.',
    'Primary elections (and caucuses) are held by political parties to choose their candidates for the General Election. Some states have "closed" primaries where only registered party members can vote. The General Election in November is the final contest where winners take office. This includes the Presidential race every four years, and Congressional races every two years.',
    'Primaries are tryouts; General is the final game.',
    'Spring/Summer (Primaries), November (General)',
    ['Party affiliation (for closed primaries)', 'Voter registration card', 'Knowledge of candidates'],
    ['Check if your state has open or closed primaries', 'Look up local ballot measures', 'Understand the electoral college system', 'Participate in caucuses if applicable'],
    'What is the purpose of a primary?', ['To elect the President', 'To choose party nominees', 'To vote on laws', 'To select judges'], 1, 'It is a selection process.'),
  step('us_b4', 4, 'Understanding the Ballot', 'Decoding the many races.',
    'Your ballot includes federal offices (President, Senate, House), state offices (Governor, State Legislature), and local positions (Mayor, School Board). It may also feature ballot initiatives or propositions—laws proposed by citizens. You can choose to vote for all offices or skip any you don\'t feel informed about. This is called "undervoting" and does not invalidate the rest of your ballot.',
    'A ballot is a menu of choices; pick what you like.',
    'Election Day',
    ['Sample Ballot review', 'Marking device (pen/screen)', 'Instruction reading'],
    ['Look up a sample ballot online before you go', 'Research "down-ballot" local races', 'Read proposition summaries carefully', 'Ask for a new ballot if you make a mistake'],
    'Can you skip a race on your ballot?', ['No', 'Yes', 'Only with a fee', 'Only with a witness'], 1, 'This is called undervoting.'),
  step('us_b5', 5, 'Voting Methods', 'How to cast your vote.',
    'You can vote in person on Election Day at your assigned polling place, or many states offer "Early Voting" in the weeks prior. Alternatively, you can vote by mail (absentee) by requesting a ballot, filling it out, and returning it via mail or a secure drop box. If you are in line when polls close on Election Day, the law requires that you be allowed to cast your vote.',
    'Pick a delivery method: in person, early, or by mail.',
    'Election Day (November)',
    ['Valid ID (depends on state)', 'Mail-in ballot application', 'Poll worker assistance'],
    ['If you are in line when polls close, stay in line!', 'Use secure drop boxes for mail ballots', 'Check your polling place location yearly', 'Volunteer as a poll worker'],
    'When is the General Election held?', ['Monday', 'Tuesday after first Monday', 'Friday', 'Sunday'], 1, 'It is always a Tuesday.'),
];

// --- UNITED KINGDOM (GB) ---
const GB_BEGINNER: ElectionStep[] = [
  step('gb_b1', 1, 'Am I Eligible to Vote?', 'UK voter eligibility rules.',
    'To vote in a UK General Election, you must be a British, Irish, or qualifying Commonwealth citizen. You must also be 18 years or older on polling day and resident in the UK. Some UK citizens living abroad can also register as overseas voters. You must not be a convicted prisoner or otherwise legally disqualified from voting.',
    'You need to be 18 and a citizen of the UK, Ireland, or the Commonwealth.',
    'Ongoing',
    ['Citizenship (UK/Irish/Commonwealth)', 'Age 18+ on polling day', 'UK Resident', 'Registered on the electoral roll', 'Not legally disqualified'],
    ['Register as soon as you move house', 'Check overseas voting rules if abroad', 'Students can register at home and uni (but only vote once)', 'Encourage friends to register'],
    'What is the minimum age for a General Election?', ['16', '18', '21', '25'], 1, 'It is 18 for national elections.'),
  step('gb_b2', 2, 'Registering to Vote', 'The UK registration system.',
    'You must be on the electoral register to vote. You can register online at gov.uk/register-to-vote in about 5 minutes. You will need your National Insurance (NI) number and passport (if living abroad). Once registered, you remain on the list unless you move house or your details change. Every year, councils send a "Canvass Communication" to verify who is living at each address.',
    'You need your NI number to register online.',
    'Until 12 days before polling',
    ['National Insurance Number', 'Current Address details', 'Passport (for overseas)', 'DOB verification'],
    ['Registering helps your credit score!', 'Update your details after marriage or name change', 'Check the register if you haven\'t voted in years', 'Opt-out of the "open register" for privacy'],
    'Where do you register?', ['Post Office', 'gov.uk', 'Police', 'Library'], 1, 'The government website is the place.'),
  step('gb_b3', 3, 'First Past the Post', 'The UK voting system.',
    'The UK uses the "First Past the Post" (FPTP) system. The country is divided into 650 local areas called constituencies. On election day, you vote for one candidate to represent your area in the House of Commons. The candidate who receives the most votes (a plurality) wins the seat, regardless of whether they have a majority. The party with the most seats usually forms the Government.',
    'The person with the most votes wins, even if it is not a majority.',
    'Election Day',
    ['Local candidate knowledge', 'Constituency identification', 'Understanding the ballot paper'],
    ['Check your local candidates online', 'Research party manifestos', 'Attend local "hustings" (debates)', 'Know which constituency you live in'],
    'How many constituencies are there?', ['450', '577', '650', '700'], 2, '650 is the current total.'),
  step('gb_b4', 4, 'Voter ID Requirements', 'New rules for 2023+.',
    'As of 2023, you must show a valid form of photo identification to vote in person at polling stations for General Elections. Accepted IDs include a UK passport, driving license, Blue Badge, or older person\'s bus pass. If you do not have an accepted ID, you can apply for a free "Voter Authority Certificate" online. These rules do not apply to postal voting.',
    'No ID, no vote (unless voting by post).',
    'Election Day (ID required)',
    ['Valid Photo ID (Passport/License)', 'Voter Authority Certificate (if needed)', 'Poll card (helpful but not required)'],
    ['Apply for a free Voter Authority Certificate if you have no ID', 'Check the list of expired IDs that are still accepted', 'Ensure the photo on your ID still looks like you', 'Remind family members about the ID rules'],
    'What is mandatory for in-person voting now?', ['Poll card', 'Photo ID', 'Utility bill', 'Nothing'], 1, 'Photo ID became mandatory in 2023.'),
  step('gb_b5', 5, 'How to Vote', 'Polling stations and deadlines.',
    'On election day, you can vote in person at your assigned polling station between 7am and 10pm. You can also apply to vote by post or by proxy (someone else voting for you). If you vote by post, your ballot must reach the local office by 10pm on election day. Polling stations are often in schools, community centers, or churches.',
    'In person, by mail, or have a friend vote for you.',
    'Election Day (7am - 10pm)',
    ['Polling station location', 'Postal ballot (if applied)', 'Proxy authorization (if applied)', 'Ink pen (provided at station)'],
    ['Post your ballot back early if voting by mail', 'You don\'t need your poll card to vote in person', 'If you forget to post your ballot, drop it at a station', 'Ask poll workers for help if needed'],
    'What time do polls close?', ['6pm', '8pm', '10pm', 'Midnight'], 2, '10pm is the closing time.'),
];

// --- SAUDI ARABIA (SA) ---
const SA_BEGINNER: ElectionStep[] = [
  step('sa_b1', 1, 'Are you eligible to participate?', 'Basic eligibility for Saudi municipal elections.',
    'Saudi citizens aged 18 and above are eligible to participate in municipal elections. Since the landmark 2015 elections, both men and women have equal rights to vote and run as candidates. You must be an ordinary resident of the municipality where you register to vote. Certain groups, such as active military personnel, are typically excluded from voting in these local contests.',
    'Saudi citizens 18 or older can vote for their local council.',
    'Ongoing',
    ['Saudi Citizenship', 'Age 18+', 'Ordinary residency in municipality', 'National ID (Mada/Absher)', 'No legal disqualifications'],
    ['Register early during designated periods', 'Keep your National ID updated', 'Verify your residency records on Absher', 'Follow official ELC announcements'],
    'When did women first vote in Saudi Arabia?', ['2005', '2011', '2015', '2020'], 2, '2015 was the landmark year.'),
  step('sa_b2', 2, 'Municipal Councils', 'Local direct elections.',
    'Municipal councils are the primary platform for citizen participation in local governance. In these elections, citizens directly elect half of the council members, while the other half are appointed by the government. These councils are responsible for overseeing city services, infrastructure development, and local land use. They serve as a vital link between the community and the Ministry of Municipal and Rural Affairs.',
    'You choose representatives to manage your city\'s infrastructure.',
    'Every 4 years',
    ['Knowledge of local candidates', 'National ID', 'Residency certificate', 'Understanding of council scope'],
    ['Follow the Ministry for official dates', 'Attend local candidate briefings', 'Check council meeting minutes online', 'Engage with current council members'],
    'How many council members are elected?', ['25%', '50%', '75%', '100%'], 1, 'Half are elected, half appointed.'),
  step('sa_b3', 3, 'The Shura Council', 'Consultative Assembly roles.',
    'The Shura Council (Majlis ash-Shura) is the formal advisory body of Saudi Arabia. It consists of 150 members, all of whom are appointed by the King for four-year terms. The council has the power to propose laws and provide recommendations on national policies and international treaties. Since 2013, a minimum of 20% of the council seats must be held by women, ensuring diverse perspectives in national policy-making.',
    'The Shura Council suggests laws and advises the leadership.',
    'Appointed every 4 years',
    ['National Policy awareness', 'Awareness of Vision 2030 goals', 'Knowledge of Shura committees', 'Current events tracking'],
    ['20% of the council must be women', 'Read the Shura Council\'s annual reports', 'Follow Shura debates on official news', 'Understand the legislative proposal process'],
    'How many members are in the Shura Council?', ['50', '100', '150', '200'], 2, '150 is the official count.'),
  step('sa_b4', 4, 'Voter Registration', 'Getting your voter card.',
    'To cast a vote, you must first register at a designated voter registration center within your municipality. You will need to present your original National ID card and provide proof of residence, such as a utility bill or house deed. Upon successful registration, you will receive a voter card or a digital confirmation. This process usually happens several months before the actual election day.',
    'Bring your ID and utility bill to a center to register.',
    'Pre-election',
    ['National ID (Physical copy)', 'Proof of Residence (Bill/Deed)', 'Voter Registration Form', 'Digital Absher account access'],
    ['Check your local municipality for locations', 'Register early to avoid last-minute crowds', 'Verify your name on the preliminary voter list', 'Keep your registration receipt safe'],
    'What is needed to register?', ['Passport', 'National ID', 'Library card', 'None'], 1, 'National ID is essential.'),
  step('sa_b5', 5, 'Local Authority Powers', 'What councils do.',
    'Municipal councils have significant influence over the daily lives of citizens. They oversee local budgets, urban planning, and the maintenance of public facilities like parks, roads, and markets. By voting, you help decide who will manage these essential services. Citizens are encouraged to report local issues and provide feedback to their council members to ensure their needs are being met effectively.',
    'Councils decide how your city spends money on roads and parks.',
    'Post-election',
    ['Active Citizenship', 'Communication channels with council', 'Knowledge of local urban plans', 'Budget awareness'],
    ['Report local issues to your council members', 'Attend public council sessions', 'Participate in municipal surveys', 'Volunteer for community cleanup initiatives'],
    'What is a council responsibility?', ['Defense', 'Urban Planning', 'Foreign Policy', 'Currency'], 1, 'They focus on local development.'),
];

// --- BRAZIL (BR) ---
const BR_BEGINNER: ElectionStep[] = [
  step('br_b1', 1, 'Is voting mandatory?', 'Brazil\'s voting rules.',
    'In Brazil, voting is a constitutional obligation for all literate citizens between the ages of 18 and 70. For those who are 16 or 17 years old, or over 70, as well as for illiterate citizens, voting is optional. Failure to vote without a valid justification can result in small fines and restrictions on obtaining a passport, taking public exams, or receiving government loans.',
    'Mandatory for adults 18-70; optional for teens and seniors.',
    'Ongoing',
    ['Brazilian Citizenship', 'Age 18-70 (Mandatory)', 'Age 16-17 or 70+ (Optional)', 'Voter Registration (Título de Eleitor)', 'No suspended political rights'],
    ['Keep your status regular to avoid fines', 'Use the e-Título app to check your status', 'Justify your absence via the app if you can\'t vote', 'Volunteer as a Mesário (poll worker) for benefits'],
    'When does voting become mandatory?', ['16', '18', '21', '70'], 1, '18 is the threshold.'),
  step('br_b2', 2, 'E-Título and Biometrics', 'Digital registration.',
    'The TSE (Superior Electoral Court) has modernized voting through the "e-Título" app, which serves as a digital version of your voter ID. It provides your polling station location and serves as identification if you have registered your biometrics. Biometric registration involves scanning your fingerprints and taking a digital photo, which significantly enhances the security of the identification process at the polls.',
    'Use the app and your fingerprint to vote securely.',
    'Pre-election',
    ['Photo ID', 'e-Título App', 'Biometric registration', 'Updated residential address', 'Smartphone for digital ID'],
    ['Register your biometrics early', 'Download the e-Título app weeks before', 'Check your polling station location in the app', 'Keep your phone charged on election day'],
    'Which app is used?', ['WhatsApp', 'e-Título', 'Gov.br', 'Wallet'], 1, 'e-Título is the official app.'),
  step('br_b3', 3, 'Electronic Voting Machines', 'Safe and disconnected.',
    'Brazil has used a 100% electronic voting system since 1996. The "Urna Eletrônica" is a purpose-built computer that is NOT connected to any network, including the internet or Bluetooth, making it highly secure against external hacking. Each machine undergoes rigorous public testing before each election. You cast your vote by simply typing the candidate\'s number and pressing the green "Confirma" button.',
    'Typing your candidate\'s number is quick and secure.',
    'Election Day',
    ['Candidate numbers (memo)', 'Poll station location', 'Valid identification', 'Knowledge of the ballot order'],
    ['Check the candidate photo on the screen', 'Press "Corrige" if you type the wrong number', 'Wait for the final "Fim" sound', 'Research candidate numbers in advance'],
    'Is the machine online?', ['Yes', 'No', 'Only for results', 'Only in cities'], 1, 'It is completely offline.'),
  step('br_b4', 4, 'The Two-Round System', 'Executive runoffs.',
    'For major executive roles like President or Governor in large cities, Brazil uses a two-round system. If no candidate receives more than 50% of the valid votes (excluding blank and null votes) in the first round, a second round is held between the top two candidates three weeks later. This ensures that the final winner has the support of a majority of the active electorate.',
    'A "final" between the top two candidates.',
    'October (1st and 2nd Rounds)',
    ['Knowledge of runoff dates', 'Understanding of valid votes', 'Candidate platforms', 'Majority support awareness'],
    ['Blank/null votes don\'t count for the total', 'Research the two remaining candidates deeply', 'Check the results on the TSE website', 'The second round is always on the last Sunday of October'],
    'When is the second round?', ['Always', 'If no majority', 'Never', 'If the King says'], 1, 'It ensures majority support.'),
  step('br_b5', 5, 'What to Bring', 'Election day rules.',
    'On election day, you must present a valid photo ID (such as a passport, driving license, or work permit) or your e-Título (if you have biometrics). It is strictly forbidden to take cell phones, cameras, or any recording devices into the voting booth to preserve the secrecy of the vote. You are encouraged to bring a small piece of paper, called a "cola," with the numbers of your chosen candidates.',
    'Leave your phone outside; bring a paper note with your numbers.',
    'Election Day',
    ['Photo ID (RG, CNH, or Passport)', 'Paper note with candidate numbers', 'e-Título (Digital ID)', 'Mask (if health rules apply)'],
    ['Cell phones are strictly banned in the booth', 'A paper "cola" is allowed and encouraged', 'Go early to avoid queues in the heat', 'Leave backpacks and large bags at home'],
    'What can you take in?', ['Cell phone', 'Camera', 'Paper note', 'None'], 2, 'A paper "cola" is allowed.'),
];

// --- FRANCE (FR) ---
const FR_BEGINNER: ElectionStep[] = [
  step('fr_b1', 1, 'Am I eligible?', 'French citizenship rules.',
    'To vote in French national elections, you must be a French citizen and at least 18 years old. You must also enjoy your civil and political rights. If you are a citizen of another European Union member state, you can vote in municipal and European elections, but not in presidential or legislative ones. Most young people are now automatically registered when they turn 18.',
    'French nationality and 18 years old are the keys.',
    'Ongoing',
    ['French Citizenship', 'Age 18+', 'Registration on electoral list', 'Civil rights enjoyment', 'Proof of identity'],
    ['18-year-olds are often registered automatically', 'Check your status on service-public.fr', 'Update address if you move within France', 'Keep your voter card safe'],
    'Minimum age?', ['16', '18', '21', '25'], 1, '18 is the legal age.'),
  step('fr_b2', 2, 'Registration', 'Getting on the list.',
    'Registration is mandatory to vote. You can register at any time of the year, but for a specific election, you must register by the 6th Friday before the first round. You can register online at service-public.fr, by mail, or in person at your local town hall (Mairie). You will need a valid ID and a proof of address less than three months old.',
    'Register at least 6 weeks before the vote.',
    'Until 6th Friday before vote',
    ['Valid ID (Passport/CNI)', 'Proof of Address (Utility bill)', 'Registration Form (Cerfa)', 'Town Hall contact'],
    ['Report address changes immediately', 'Register online for the fastest experience', 'Ensure your proof of address is recent', 'Ask for a receipt after registration'],
    'Where to register?', ['Police', 'Town Hall', 'Post Office', 'Bank'], 1, 'Town hall (Mairie) is the place.'),
  step('fr_b3', 3, 'The Two-Round System', 'Runoff mechanics.',
    'France uses a two-round uninominal voting system for presidential and legislative elections. If no candidate wins an absolute majority (over 50%) in the first round, a second round is held two weeks later between the top two candidates. This system encourages the formation of broad political alliances and ensures that the final winner has significant majority support.',
    'Round 1 is for your heart; Round 2 is for your choice.',
    'Sunday and Sunday + 14 days',
    ['Knowledge of runoff dates', 'Understanding of majority rules', 'Candidate platform comparison', 'Dual-ballot strategy'],
    ['The second round is a direct duel', 'Check if your preferred candidate made the cut', 'Abstention in round 2 still impacts the outcome', 'Understand the "republican front" concept'],
    'How many in the 2nd round?', ['All', '3', '2', '1'], 2, 'It is a duel.'),
  step('fr_b4', 4, 'How to Vote', 'Polling station rituals.',
    'On election day, you go to your assigned polling station. You must take a ballot for each candidate (to preserve secrecy) and an envelope. You then enter the voting booth (mandatory), put your chosen ballot in the envelope, and exit. After presenting your ID and voter card to the officials, you slide the envelope into the transparent ballot box. The official then announces "A voté!" while signing the register.',
    'The president says "A voté!" after you slide the envelope.',
    'Election Day',
    ['Photo ID (Passport/CNI)', 'Voter Card (recommended)', 'Knowledge of station location', 'Assigned booth number'],
    ['Booth passage is mandatory', 'Take at least two different ballots', 'Leave your phone in your pocket', 'Polling stations usually open at 8am'],
    'Official phrase?', ['Done', 'A voté!', 'Bravo', 'Next'], 1, 'A voté! is the standard.'),
  step('fr_b5', 5, 'President and Parliament', 'The goals of the vote.',
    'The President of the Republic is the head of state, elected by direct universal suffrage for a five-year term, known as the "Quinquennat." The National Assembly is the lower house of Parliament, where deputies make and vote on laws. If the President and the Assembly majority are from different parties, a "cohabitation" occurs, requiring the President to appoint a Prime Minister from the opposing majority.',
    'You vote for the leader and the law-makers.',
    'Every 5 years',
    ['Candidate platform awareness', 'Knowledge of institutional roles', 'Election calendar awareness', 'Political party understanding'],
    ['A cohabitation occurs when they are from different parties', 'The President cannot serve more than two terms', 'Legislative elections usually follow the Presidential one', 'Research the powers of the Prime Minister'],
    '5-year mandate?', ['Triennat', 'Quinquennat', 'Septennat', 'None'], 1, 'Quinquennat is the name.'),
];

// --- GERMANY (DE) ---
const DE_BEGINNER: ElectionStep[] = [
  step('de_b1', 1, 'Who can vote?', 'German eligibility.',
    'To vote in German federal elections (Bundestagswahl), you must be a German citizen and at least 18 years old on election day. You must have lived in Germany for at least three months prior to the election. Residents of other EU countries living in Germany can vote in local and European elections, but only German citizens can participate in national elections. You must also not be disqualified from voting by a court order.',
    'Citizenship and 18 years old to join.',
    'Ongoing',
    ['German Citizenship', 'Age 18+ by election day', '3 months residency in Germany', 'Entry in the electoral register', 'No disqualification by court order'],
    ['You will get a notification by mail automatically', 'Check your local Bürgeramt if you haven\'t received mail', 'Apply for registration if you recently returned from abroad', 'Keep your ID card (Personalausweis) valid'],
    'Age?', ['16', '18', '21', '25'], 1, '18 for national elections.'),
  step('de_b2', 2, 'Notification', 'The paper invitation.',
    'About 4 to 6 weeks before the election, every eligible voter receives a "Wahlbenachrichtigung" (election notification) by mail. This letter confirms that you are in the electoral register and tells you the address of your specific polling station. It also includes an application form if you wish to vote by post instead of in person. You should bring this letter and your ID card with you to the polling station.',
    'The letter tells you exactly where to go.',
    '4-6 weeks before',
    ['Registration at current address', 'Mailbox access', 'Valid ID card (Personalausweis)', 'Polling station address'],
    ['Keep the letter safe; it makes voting faster', 'Verify the polling station address early', 'Apply for postal voting if you are traveling', 'Contact your local authority if the mail is missing'],
    'How do you know where to go?', ['Newspaper', 'Mail notification', 'Search online', 'None'], 1, 'The mail notification.'),
  step('de_b3', 3, 'Two Votes', 'Personalized proportionality.',
    'Germany uses a "Personalized Proportional Representation" system where each voter has two votes. The first vote (Erststimme) is for a local candidate in your constituency; the winner here gets a direct seat. The second vote (Zweitstimme) is for a political party list and is much more important, as it determines the overall percentage of seats each party will have in the Bundestag. This system ensures that the parliament reflects the national popular vote.',
    'Local representative vs. National party strength.',
    'Election Day',
    ['Knowledge of local candidates', 'Party platform awareness', 'Understanding of the 5% rule', 'Ballot marking instructions'],
    ['You can split your votes between parties', 'Research the local candidate\'s record', 'The 2nd vote determines the Chancellor\'s party power', 'Ensure you mark only one box for each vote'],
    'Which vote is more important?', ['1st', '2nd', '3rd', 'None'], 1, 'The 2nd vote decides seat counts.'),
  step('de_b4', 4, 'The 5% Hurdle', 'The entry barrier.',
    'To prevent political fragmentation and ensure a stable government, a party must receive at least 5% of the national second votes to enter the Bundestag. If a party fails to meet this threshold, it receives no seats unless it wins at least three direct constituency seats via the first vote. This "Sperrklausel" (blocking clause) encourages voters to consider the viability of smaller parties.',
    'It prevents too many tiny parties from making government hard.',
    'Election Day',
    ['Threshold awareness', 'Coalition knowledge', 'Political stability understanding', 'Current poll tracking'],
    ['Helps keep the parliament stable', 'Research "small" parties carefully', 'Consider if your party will likely pass 5%', 'Understand how "wasted" votes impact coalitions'],
    'Threshold?', ['1%', '3%', '5%', '10%'], 2, '5% is the rule.'),
  step('de_b5', 5, 'Mail Voting', 'Voting from your couch.',
    'If you cannot or do not want to go to a polling station, you can apply for "Briefwahl" (postal voting). Once you receive your documents, you mark the ballot, place it in the blue envelope, and then place that inside the red return envelope along with your signed voting card. No postage stamp is needed if mailed within Germany. Your ballot must reach the election office by 6pm on election Sunday.',
    'Fill out the ballot, put it in the red envelope, and mail it.',
    'Before Election Day',
    ['Postal application form', 'Marked ballot paper', 'Signed polling card (Wahlschein)', 'Blue and Red envelopes'],
    ['Mail it back early; it must arrive by Sunday 6pm', 'Ensure you sign the polling card personally', 'Do not forget to put the ballot in the blue envelope first', 'Drop it in any yellow Deutsche Post box'],
    'Envelope color?', ['Blue', 'Red', 'Yellow', 'White'], 1, 'Red is the return envelope.'),
];

// --- AUSTRALIA (AU) ---
const AU_BEGINNER: ElectionStep[] = [
  step('au_b1', 1, 'Is voting compulsory?', 'Australia\'s unique rule.',
    'In Australia, voting is a legal requirement for all eligible citizens aged 18 and over. This "compulsory voting" system has been in place for federal elections since 1924. If you fail to vote without a valid and sufficient reason, you may be issued a fine (currently around $20 for the first offense). This policy ensures high voter turnout and that the government represents a broad cross-section of the population.',
    'You must vote by law if you are 18+.',
    'Ongoing',
    ['Australian Citizenship', 'Age 18+ on polling day', 'Enrollment with the AEC', 'No mental incapacity (legal definition)', 'No serving a prison sentence of 3+ years'],
    ['Enrol as soon as you turn 18', 'Update your details on the AEC website', 'Check your enrollment status before every election', 'Know your rights for assistance at the booth'],
    'Is voting mandatory?', ['Yes', 'No', 'Only for men', 'Only for landowners'], 0, 'Australia was a pioneer in compulsory voting.'),
  step('au_b2', 2, 'Preferential Voting', 'The 1, 2, 3 system.',
    'Australia uses a "Preferential Voting" system, which is a form of ranked-choice voting. Instead of just picking one candidate, you rank them in order of preference (1, 2, 3...). If your first-choice candidate is eliminated, your vote is transferred to your next preferred candidate. This continues until one candidate receives an absolute majority of votes, ensuring the winner has the broadest possible support.',
    'Don\'t just pick one; rank them all.',
    'Election Day',
    ['Ranked choice knowledge', 'Ballot marking (Numbers only)', 'Candidate preference list', 'Understanding of major vs minor parties'],
    ['Your vote is never "wasted" in this system', 'Mark EVERY box for a valid House vote', 'Check the AEC "How to Vote" guide', 'Research independent candidates carefully'],
    'How do you mark the ballot?', ['Checkmark', 'Numbers (1, 2, 3)', 'X', 'Signature'], 1, 'Numbers are required.'),
  step('au_b3', 3, 'The House and Senate', 'Two ballots, two colors.',
    'On federal election day, you will receive two separate ballot papers. The green ballot is for the House of Representatives, where you choose a local member for your specific electorate. The large white ballot is for the Senate, where you choose representatives for your whole state or territory. For the Senate, you can choose to vote "above the line" (for a party) or "below the line" (for individual candidates).',
    'Two houses, two different voting styles.',
    'Election Day',
    ['House (Green) ballot', 'Senate (White) ballot', 'State/Territory identification', 'Pencil (provided at booth)'],
    ['Vote "above the line" for easy Senate voting', 'Use numbers 1-6 above the line for Senate', 'Ensure you follow the instructions on the ballot paper', 'Ask for help if you find the Senate ballot confusing'],
    'Green ballot color?', ['House', 'Senate', 'Mayor', 'None'], 0, 'Green is for the House of Reps.'),
  step('au_b4', 4, 'The Sausage Sizzle', 'Election day culture.',
    'Voting in Australia is often a community event. Most polling stations, located in local primary schools and community halls, host a "Democracy Sausage" sizzle run by volunteers. Many also hold cake stalls and school fetes. This tradition has become a beloved part of the Australian election day experience, with websites even tracking which polling booths have the best sausage sizzles.',
    'Vote, then get a snack.',
    'Election Day',
    ['Hunger!', 'Small change/cash', 'Community spirit', 'Saturday morning free time'],
    ['Look for the best sausage sizzle in your area', 'Bring cash for the sausage sizzle and cakes', 'Vote early to get the freshest sausages', 'Check "Democracy Sausage" maps online'],
    'What is a "Democracy Sausage"?', ['A law', 'A snack', 'A candidate', 'A medal'], 1, 'It is a beloved tradition.'),
  step('au_b5', 5, 'Where to Vote', 'Local booths.',
    'Federal elections in Australia are always held on a Saturday. You can vote at any polling place in your state or territory on election day, or you can visit an early voting center in the weeks prior if you cannot make it on the day. Polling places are open from 8am to 6pm. Postal voting and telephone voting are also available for those with specific needs or living in remote areas.',
    'Saturdays are for voting.',
    'Saturday Election Day (8am - 6pm)',
    ['Polling station location', 'Electoral district knowledge', 'Voter identification (not always required)', 'Early voting eligibility (if applicable)'],
    ['Absentee voting is available if you are out of your district', 'Check the AEC website for booth locations', 'Avoid the lunchtime rush for shorter queues', 'Keep your voter registration card handy'],
    'Usual day for elections?', ['Tuesday', 'Saturday', 'Sunday', 'Friday'], 1, 'Saturday is the standard.'),
];

// --- CANADA (CA) ---
const CA_BEGINNER: ElectionStep[] = [
  step('ca_b1', 1, 'Am I Eligible?', 'Canadian citizenship rules.',
    'To vote in a Canadian federal election, you must be a Canadian citizen and at least 18 years old on election day. You must also be registered on the National Register of Electors. Canadians living abroad can vote by special ballot regardless of how long they have been away. Permanent residents and other non-citizens are not eligible to vote in federal elections.',
    'Citizenship and 18 years old.',
    'Ongoing',
    ['Canadian Citizenship', 'Age 18+ by election day', 'National Register of Electors entry', 'Proof of identity', 'Proof of address'],
    ['Check your registration at Elections Canada', 'Register at age 17 to be ready for 18', 'Apply for citizenship if you are a resident', 'Know your rights if you are an overseas voter'],
    'Age?', ['16', '18', '21', '25'], 1, '18 is the law.'),
  step('ca_b2', 2, 'Registration', 'Getting on the list.',
    'Elections Canada maintains the voter list. You can check if you are registered, update your information, or register for the first time online. If you are not registered by election day, you can still register at the polling station just before you vote, as long as you have the required ID. Most Canadians are registered automatically through tax filings if they give consent.',
    'Registration is easy and can even be done when you arrive to vote.',
    'Until Election Day',
    ['ID and Proof of Address', 'Voter Information Card (if received)', 'Tax filing consent (optional)', 'Online registration access'],
    ['Registering in advance saves time at the polls', 'Check your Voter Information Card for accuracy', 'Bring your card and ID together', 'Ask for a language interpreter if needed'],
    'Can you register at the polls?', ['Yes', 'No', 'Only in Yukon', 'Only with a lawyer'], 0, 'Canada allows same-day registration.'),
  step('ca_b3', 3, 'First Past the Post', 'Constituency wins.',
    'Canada uses the "First-Past-the-Post" system for federal elections. The country is divided into 338 electoral districts, also known as ridings. Voters in each riding elect one Member of Parliament (MP) to represent them in the House of Commons. The candidate with the most votes in the riding wins the seat. The leader of the party with the most seats usually becomes the Prime Minister.',
    'Whoever gets the most votes in your area becomes your MP.',
    'Election Day',
    ['Riding/District knowledge', 'Candidate names', 'Party platform summaries', 'Understanding of minority governments'],
    ['The party with the most seats usually forms the government', 'Research the local candidate\'s priorities', 'Understand how a "Confidence" vote works', 'Know the boundaries of your riding'],
    'How many ridings?', ['300', '338', '400', '450'], 1, '338 is the current count.'),
  step('ca_b4', 4, 'Ways to Vote', 'Advance and mail.',
    'Elections Canada provides several ways to vote. You can vote in person on election day at your assigned polling station, or during four days of advance polling. You can also vote at any Elections Canada office across the country before a specific deadline. Finally, you can vote by mail using a special ballot, which is a popular option for students and travelers.',
    'Vote early if you are busy on election day.',
    'Election Day and 4 days of advance polling',
    ['Voter Information Card', 'Special ballot application (for mail)', 'Polling station location', 'Valid identification'],
    ['Bring your Voter Information Card to speed things up', 'Vote at advance polls to avoid crowds', 'Apply for mail-in ballots weeks in advance', 'Check office hours if voting at an EC office'],
    'Advance polling?', ['Yes', 'No', 'Only for military', 'Only for seniors'], 0, 'Advance polls are open for everyone.'),
  step('ca_b5', 5, 'Required ID', 'Proving who you are.',
    'To vote, you must prove your identity and address. There are three options: 1) Present one government-issued photo ID with your name and current address (like a driver\'s license). 2) Present two pieces of ID, both with your name and at least one with your current address (like a health card and a utility bill). 3) If you have no ID, you can declare your identity in writing and have someone else "vouch" for you.',
    'You need ID, but there are many ways to prove it.',
    'Election Day',
    ['Accepted ID (Option 1, 2, or 3)', 'Utility bill or bank statement', 'Witness for vouching (if needed)', 'Voter Information Card'],
    ['Check the list of accepted IDs at elections.ca', 'Ensure your address is current on your ID', 'Someone can vouch for you if you lack ID', 'Expired ID is sometimes accepted (check rules)'],
    'Vouching?', ['Yes', 'No', 'Only in 2024', 'None'], 0, 'Someone can vouch for you if you lack ID.'),
];

// --- FALLBACK REGISTRY ---
export const FALLBACK_GUIDES: Record<string, Record<KnowledgeLevel, ElectionStep[]>> = {
  IN: { beginner: IN_BEGINNER, intermediate: IN_BEGINNER, advanced: IN_BEGINNER },
  US: { beginner: US_BEGINNER, intermediate: US_BEGINNER, advanced: US_BEGINNER },
  GB: { beginner: GB_BEGINNER, intermediate: GB_BEGINNER, advanced: GB_BEGINNER },
  SA: { beginner: SA_BEGINNER, intermediate: SA_BEGINNER, advanced: SA_BEGINNER },
  FR: { beginner: FR_BEGINNER, intermediate: FR_BEGINNER, advanced: FR_BEGINNER },
  DE: { beginner: DE_BEGINNER, intermediate: DE_BEGINNER, advanced: DE_BEGINNER },
  BR: { beginner: BR_BEGINNER, intermediate: BR_BEGINNER, advanced: BR_BEGINNER },
  AU: { beginner: AU_BEGINNER, intermediate: AU_BEGINNER, advanced: AU_BEGINNER },
  CA: { beginner: CA_BEGINNER, intermediate: CA_BEGINNER, advanced: CA_BEGINNER },
};

/**
 * Retrieves fallback guide for a country and knowledge level.
 * High-performance library serving 9 countries in <50ms.
 */
export function getFallbackGuide(
  countryCode: string,
  knowledgeLevel: KnowledgeLevel
): ElectionStep[] | null {
  const code = countryCode.toUpperCase();
  const countryGuides = FALLBACK_GUIDES[code];
  
  if (countryGuides) {
    const steps = countryGuides[knowledgeLevel];
    if (steps) return [...steps];
  }

  // Final fallback (UK version as high-quality default)
  return FALLBACK_GUIDES.GB[knowledgeLevel];
}
